language: php

php:
  - 7.3

addons:
  chrome: stable

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest 
  - php artisan key:generate

before_script:
 # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
  - ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
  - sleep 5
script:
  - php artisan dusk